version: '3.8'

services:
  order-db:
    image: mysql:8.0
    container_name: order-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: orderpassword
      MYSQL_DATABASE: orderdb
    ports:
      - "3308:3306"
    volumes:
      - order_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10


volumes:
  order_data: