server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3308/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: orderpassword

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  config:
    import: classpath:error-message.properties
user:
  service:
    url: "https://localhost:8080"